import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/components/utils/ThemeProvider";
import Navbar from "@/components/nav/NavBar";
import AcceptCookies from "@/components/utils/AcceptCookies";
import BackToTop from "@/components/utils/BackToTop";

import Footer from "@/components/utils/Footer";
import Parallax from "@/components/home/Parallax";

// Jakarta Font Setup
const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fashion Brand - fullstack nextjs",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakarta.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <AcceptCookies />
          <BackToTop />
          <Parallax />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
